# Generated by Django 3.1 on 2020-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('times', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Writeblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('blogtopic', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('avatar', models.ImageField(upload_to='')),
                ('blogpost', models.TextField()),
                ('readtime', models.CharField(max_length=50)),
                ('submitdate', models.DateTimeField()),
            ],
        ),
    ]
