# Generated by Django 3.1 on 2020-08-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='times',
            new_name='time',
        ),
    ]
