# Generated by Django 3.0.1 on 2020-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20200814_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeblog',
            name='avatar',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
