# Generated by Django 3.0.1 on 2020-08-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_auto_20200814_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeblog',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avater'),
        ),
    ]
